spring:
  datasource:
    username: snail_ino
    password: HBwkaY8btmQCMm2jvzjU5w
    url: jdbc:postgresql://free-tier.gcp-us-central1.cockroachlabs.cloud:26257/first-exp-5622.safe_home?sslmode=verify-full&sslrootcert=C:\Users\bgy42\AppData\Roaming\.postgresql\root.crt
    driver-class-name: org.postgresql.Driver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:

mybatis:
  type-aliases-package: com.cusehack.criminal_alert.dao.beans
  configuration:
    map-underscore-to-camel-case: true
